---
openapi: 3.0.0
info:
  title: LineSetupAPI
  description: questa API permette ad aziende utenti di impostare nuove linee e/o modificare linee esistenti
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/Ingsoft2project/LineSetup/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /Lines:
    get:
      description: permette di ottenere le linee disponibili per il servizio trasporti selezionato
      parameters:
      - name: companyId
        in: query
        description: filtra le linee disponibili visualizzando esclusivamente le linee relative all'azienda utente che vuole modificare una o più linee
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Succesful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /Line/Setup:
    post:
      description: Imposta una nuova linea
      requestBody:
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/Lines'
              - type: object
              - required:
                - BusStopTotal
                - Number
              - properties:
                  number:
                    type: integer
                    example: 10
                  BusStopTotal:
                    type: integer
                    example: 12
        required: true
      responses:
        "201":
          description: Linea inserita correttamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LineSelf'
        "400":
          description: Richiesta invalida. Parametri non validi e/o parametri obbligatori mancanti
          content:
            application/json:
              schema:
                required:
                - message
                type: object
                properties:
                  message:
                    type: string
                    description: Messaggio dell'errore
                    example: Il campo "Number" è obbligatorio
                  fieldErrors:
                    type: array
                    description: I campi che hanno generato l'errore con il relativo messaggio
                    example:
                    - FieldName: number
                    - FieldErrorMessage: Il campo "number" è obbligatorio
                    items:
                      $ref: '#/components/schemas/LineError'
                example:
                  message: dwg
        "409":
          description: Linea già esistente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LineError'
components:
  schemas:
    SelfObj:
      type: object
      properties:
        self:
          type: string
          example: /api/v1/object/8452
    Lines:
      required:
      - ArrivalTime
      - BusStopName
      - BusStopOrder
      - BusStopTotal
      - Number
      type: object
      properties:
        Number:
          type: integer
          example: 10
        BusStopTotal:
          type: integer
          example: 12
        BusStopName:
          type: string
          example: Piazza Dante
        BusStopOrder:
          type: integer
          example: 15
        ArrivalTime:
          type: string
          example: 18:00
    LineSelf:
      type: object
      allOf:
      - $ref: '#/components/schemas/SelfObj'
      - $ref: '#/components/schemas/Lines'
    LineError:
      required:
      - FieldErrorMessage
      - FieldName
      type: object
      properties:
        FieldName:
          type: string
          description: Nome del campo che ha generato l'errore
        FieldErrorMessage:
          type: string
          description: Errore specifico del campo
      example:
        FieldName: NumeroLinea
        FieldErrorMessage: la linea numero "5" è già esistente
  responses:
    "400BadRequest":
      description: Richiesta invalida. Parametri non validi e/o parametri obbligatori mancanti
      content:
        application/json:
          schema:
            required:
            - message
            type: object
            properties:
              message:
                type: string
                description: Messaggio dell'errore
                example: Il campo "Number" è obbligatorio
              fieldErrors:
                type: array
                description: I campi che hanno generato l'errore con il relativo messaggio
                example:
                - FieldName: number
                - FieldErrorMessage: Il campo "number" è obbligatorio
                items:
                  $ref: '#/components/schemas/LineError'
            example:
              message: dwg
